### ISSUE TITLE
Internal Server Error when clicking on the menu item "Raffle"

### ISSUE THREAD

**Issue by bpcurse** [pretix/pretix-cliques#3]
Does anyone have an idea what could be the cause of this error or how to debug it further?
Versions: Pretix 3.13.0 using mariaDB / pretix-cliques cloned today from github

```
Dez 20 17:07:07 ****** gunicorn[16510]: ERROR 2020-12-20 16:07:07,382 django.request log Internal Server Error: /control/event/test/test212/cliques/raffle/
Dez 20 17:07:07 ****** gunicorn[16510]: Traceback (most recent call last):
Dez 20 17:07:07 ****** gunicorn[16510]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
Dez 20 17:07:07 ****** gunicorn[16510]:     response = get_response(request)
Dez 20 17:07:07 ****** gunicorn[16510]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
Dez 20 17:07:07 ****** gunicorn[16510]:     response = self.process_exception_by_middleware(e, request)
Dez 20 17:07:07 ****** gunicorn[16510]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
Dez 20 17:07:07 ****** gunicorn[16510]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Dez 20 17:07:07 ****** gunicorn[16510]:   File "/var/pretix/venv/lib/python3.7/site-packages/pretix/control/permissions.py", line 28, in wrapper
Dez 20 17:07:07 ****** gunicorn[16510]:     return function(request, *args, **kw)
Dez 20 17:07:07 ****** gunicorn[16510]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
Dez 20 17:07:07 ****** gunicorn[16510]:     return self.dispatch(request, *args, **kwargs)
Dez 20 17:07:07 ****** gunicorn[16510]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
Dez 20 17:07:07 ****** gunicorn[16510]:     return handler(request, *args, **kwargs)
Dez 20 17:07:07 ****** gunicorn[16510]:   File "/var/pretix/venv/lib/python3.7/site-packages/pretix_cliques-1.0.0-py3.7.egg/pretix_cliques/views.py", line 412, in get
Dez 20 17:07:07 ****** gunicorn[16510]:     return FormView.get(self, request, *args, **kwargs)
Dez 20 17:07:07 ****** gunicorn[16510]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/views/generic/edit.py", line 133, in get
Dez 20 17:07:07 ****** gunicorn[16510]:     return self.render_to_response(self.get_context_data())
Dez 20 17:07:07 ****** gunicorn[16510]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/views/generic/edit.py", line 66, in get_context_data
Dez 20 17:07:07 ****** gunicorn[16510]:     kwargs['form'] = self.get_form()
Dez 20 17:07:07 ****** gunicorn[16510]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/views/generic/edit.py", line 33, in get_form
Dez 20 17:07:07 ****** gunicorn[16510]:     return form_class(**self.get_form_kwargs())
Dez 20 17:07:07 ****** gunicorn[16510]:   File "/var/pretix/venv/lib/python3.7/site-packages/pretix_cliques-1.0.0-py3.7.egg/pretix_cliques/views.py", line 369, in __init__
Dez 20 17:07:07 ****** gunicorn[16510]:     del self.fields['all_subevents']
Dez 20 17:07:07 ****** gunicorn[16510]: KeyError: 'all_subevents'
```

**Comment by raphaelm** [comment]
I think the line in which the exception occurrs is just plain wrong and should be removed

**Comment by wussler** [comment]
[Forked](https://github.com/wussler/pretix-cliques), removing the line does indeed solve this. Seems to be referenced nowhere else.

**Comment by raphaelm** [comment]
Great! Care to create a PR?
